target-version = "py39"
line-length = 88

[lint]
extend-select = [
  "UP",  # pyupgrade
#   "D",   # pydocstyle
  # "E4",
  # "E7",
  # "E9",
  "E",
  "F",
  "I",
  "PL",
]
ignore = ["PLR0913"]

[lint.pydocstyle]
convention = "numpy"

[format]
docstring-code-format = true
docstring-code-line-length = 20

